name: Build Windows EXE Only

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Windows EXE
        run: flutter build windows --release

      - name: Upload Windows EXE
        uses: actions/upload-artifact@v4
        with:
          name: Windows-App-Release
          path: build/windows/runner/Release/
